
version: '3'

services:
  mongo-express:
    container_name: "dbweb"
    image: mongo-express
    ports:
      - "20001:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    links:
      - db 
    networks:
      - mongo-compose-network

  db:
    image: mongo
    container_name: "db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
    networks:
      - mongo-compose-network


  backend:
    tty: true
    build: ./backend/
    container_name: "backend"
    environment:
      - "TZ=Japan"
    volumes:
      - backend-sync:/backend
    ports:
      - "20002:80"
    links:
      - db
    restart: always
    expose:
        - "80"
    networks:
      - mongo-compose-network



networks: 
    mongo-compose-network:
      driver: bridge
volumes:
    backend-sync:
        external: true 
